spring:
  application:
    name: spring-project
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: hossein
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql : true
    show-sql: true
server:
  port: 8080
  error:
    include-message: always
    

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include:
        - "health"
        - "info"

jwt:
  token:
    secret: "hkh_is_REAL_!^!#$^!$^!$%!#$%%#%^*$*$%&@#@#%$%!#^$@$&@^*#%(#&(#%^*@&%^!#$^!$#^@%&@$&@$^*@$^&%^@#$%))_hkh_is_REAL_!^!#$^!$^!$%!#$%%#%^*$*$%&@#@#%$%!#^$@$&@^*#%(#&(#%^*@&%^!#$^!$#^@%&@$&@$^*@$^&%^@#$%))_hkh_is_REAL_!^!#$^!$^!$%!#$%%#%^*$*$%&@#@#%$%!#^$@$&@^*#%(#&(#%^*@&%^!#$^!$#^@%&@$&@$^*@$^&%^@#$%))"