services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: hossein
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  spring-project:
    container_name: springOfSpring
    image: blackpuss/spring-project
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    command: 
networks:
  db:
    driver: bridge

volumes:
  db:
